<a href="https://colab.research.google.com/github/leenalokhande/data-science/blob/main/assignment_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1 numpy program to get numpy version
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [ ]:
print("checking wether none of the element of a given array is zero")
x=np.all(x)
x

checking wether none of the element of a given array is zero


True

In [ ]:
#3 to create elemnt wise comparison of two given array
x=np.array([1,2,3,4,])
y=np.array([5,6,7,8])
print(x>=y)
print(x<=y)
print(x==y)

[False False False False]
[ True  True  True  True]
[False False False False]


In [ ]:
#4. create an array with valueand determine size of array
a=np.array([1,7,13,105])
a
a.nbytes

32

In [ ]:
#5 creaate an array of integers from 30 to 70
a=np.arange(30,71)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
#6 create an array of all even integer
x=np.arange(30,71,2)
print(x)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
#7 create 3*3 identity matrix
a=np.identity(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
from re import A
#8 create array 3*4 array
import numpy as np
a=np.arange(10,22).reshape((3,4))
print("original array:")
print("each elemen of array is")
for x in np.nditer(a):
   print(x,end= "")

original array:
each elemen of array is
101112131415161718192021